baseURL = "https://itscooper-samm.sandbox1.cloud/"
languageCode = "en-us"
title = "OWASP SAMM 2.0"
contentDir = "../v2.0/beta"
theme = "hugo-paper"
[taxonomies]
  business_function = "business_functions"
